### ISSUE TITLE
Python 3.3.2 SyntaxError on twitter-text-py 2.0.0

### ISSUE THREAD

**Issue by ghost** [dryan/twitter-text-py#21]
``` python
$ python
Python 3.3.2 (default, Sep  6 2013, 09:30:10) 
[GCC 4.8.1 20130725 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twitter_text
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/twitter_text/__init__.py", line 3, in <module>
    from twitter_text.autolink import Autolink
  File "/usr/lib/python3.3/site-packages/twitter_text/autolink.py", line 309
    display_url_sans_ellipses = re.sub(ur'…', u'', display_url)
                                             ^
SyntaxError: invalid syntax
```

**Comment by dryan** [comment]
If you'd be willing to help rework the module to be both 2 and 3 compatible, that would be awesome.

**Comment by chengjun** [comment]
to solve the problem, it seems that you can just replace **ur** as **r**, but there are still more problems.
